# Deploy OpenShift Container Platform
# Uses Fork of https://github.com/microsoft/openshift-origin
# https://github.com/ATALLC/openshift-origin

trigger:
- none

stages:
- stage: Deploy
  displayName: Deploy
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: git checkout existing-network-3.9
          - script: git submodule update --init
          #tar folders for staging in azure storage
          - task: ArchiveFiles@2
            displayName: 'Archiving Ansible RPMs'
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/ansible-rpms'
              includeRootFolder: false
              archiveType: 'tar'
              archiveFile: '$(Build.SourcesDirectory)/ansible-rpms.tar'
              replaceExistingArchive: true
          - task: ArchiveFiles@2
            displayName: 'Archiving openshift ansible scripts'
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/openshift-ansible'
              includeRootFolder: false
              archiveType: 'tar'
              archiveFile: '$(Build.SourcesDirectory)/openshift-ansible.tar'
              replaceExistingArchive: true
          - task: ArchiveFiles@2
            displayName: 'Archiving openshift container platform playbooks'
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/openshift-container-platform-playbooks'
              includeRootFolder: false
              archiveType: 'tar'
              archiveFile: '$(Build.SourcesDirectory)/openshift-container-platform-playbooks.tar'
              replaceExistingArchive: true
          - script: |
              ./scripts/downloadOpenshiftOriginRpms.sh $(Build.SourcesDirectory)
            displayName: 'Download openshift origin rpms'
          - task: ArchiveFiles@2
            displayName: 'Archiving openshift origin rpms'
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)/openshift-origin-rpms'
              includeRootFolder: false
              archiveType: 'tar'
              archiveFile: '$(Build.SourcesDirectory)/openshift-origin-rpms.tar'
              replaceExistingArchive: true
          - script: |
              rm -rf $(Build.SourcesDirectory)/openshift-origin-rpms
            displayName: 'Remove rpms folder'
          - task: ArchiveFiles@2
            displayName: 'Archive source folder for staging in Azure blob storage for pushing to CCE if build is successful, excludes docker images'
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)'
              includeRootFolder: false
              archiveType: 'tar'
              archiveFile: '$(Build.SourcesDirectory)/openshift-origin.tar'
              replaceExistingArchive: true
          - script: |
              ./scripts/downloadDockerArchives.sh
            displayName: 'Download openshift origin docker images'
          - task: AzurePowerShell@4
            displayName: 'Upload the deployable assets to blob store and generate SAS links'
            inputs:
              azureSubscription: $(RESOURCE_MANAGER_SERVICE_CONNECTION)
              scriptType: 'FilePath'
              scriptPath: 'scripts/deployAssets.ps1'
              scriptArguments: $(Build.SourcesDirectory) $(STORAGE_ACCOUNT_NAME) $(STORAGE_ACCOUNT_KEY) $(CONTAINER_NAME)
              azurePowerShellVersion: 'LatestVersion'
          - script: |
              ANSIBLE_URI=`cat scripts/ANSIBLE_LINK.txt`
              echo $ANSIBLE_URI
              echo "##vso[task.setvariable variable=ANSIBLE_URI]'$ANSIBLE_URI'"
              OPENSHIFT_ORIGIN_RPMS_URI=`cat scripts/OPENSHIFT_ORIGIN_RPMS_LINK.txt`
              echo $OPENSHIFT_ORIGIN_RPMS_URI
              echo "##vso[task.setvariable variable=OPENSHIFT_ORIGIN_RPMS_URI]'$OPENSHIFT_ORIGIN_RPMS_URI'"
              OPENSHIFT_ANSIBLE_URI=`cat scripts/OPENSHIFT_ANSIBLE_LINK.txt`
              echo $OPENSHIFT_ANSIBLE_URI
              echo "##vso[task.setvariable variable=OPENSHIFT_ANSIBLE_URI]'$OPENSHIFT_ANSIBLE_URI'"
              OPENSHIFT_CONTAINER_PLATFORM_PLAYBOOKS_URI=`cat scripts/OPENSHIFT_CONTAINER_PLATFORM_PLAYBOOKS_LINK.txt`
              echo $OPENSHIFT_CONTAINER_PLATFORM_PLAYBOOKS_URI
              echo "##vso[task.setvariable variable=OPENSHIFT_CONTAINER_PLATFORM_PLAYBOOKS_URI]'$OPENSHIFT_CONTAINER_PLATFORM_PLAYBOOKS_URI'"
              CLUSTERNODE_JSON_URI=`cat scripts/CLUSTERNODE_JSON_LINK.txt`
              echo $CLUSTERNODE_JSON_URI
              echo "##vso[task.setvariable variable=CLUSTERNODE_JSON_URI]'$CLUSTERNODE_JSON_URI'"
              OPENSHIFT_DEPLOY_JSON_URI=`cat scripts/OPENSHIFT_DEPLOY_JSON_LINK.txt`
              echo $OPENSHIFT_DEPLOY_JSON_URI
              echo "##vso[task.setvariable variable=OPENSHIFT_DEPLOY_JSON_URI]'$OPENSHIFT_DEPLOY_JSON_URI'"
              DEPLOY_OPENSHIFT_SH_URI=`cat scripts/DEPLOY_OPENSHIFT_SH_LINK.txt`
              echo $DEPLOY_OPENSHIFT_SH_URI
              echo "##vso[task.setvariable variable=DEPLOY_OPENSHIFT_SH_URI]'$DEPLOY_OPENSHIFT_SH_URI'"
              MASTER_PREP_SH_URI=`cat scripts/MASTER_PREP_SH_LINK.txt`
              echo $MASTER_PREP_SH_URI
              echo "##vso[task.setvariable variable=MASTER_PREP_SH_URI]'$MASTER_PREP_SH_URI'"
              NODE_PREP_SH_URI=`cat scripts/NODE_PREP_SH_LINK.txt`
              echo $NODE_PREP_SH_URI
              echo "##vso[task.setvariable variable=NODE_PREP_SH_URI]'$NODE_PREP_SH_URI'"
              INFRA_PREP_SH_URI=`cat scripts/INFRA_PREP_SH_LINK.txt`
              echo $INFRA_PREP_SH_URI
              echo "##vso[task.setvariable variable=INFRA_PREP_SH_URI]'$INFRA_PREP_SH_URI'"
              DOCKER_PREP_SH_URI=`cat scripts/DOCKER_PREP_SH_LINK.txt`
              echo $DOCKER_PREP_SH_URI
              echo "##vso[task.setvariable variable=DOCKER_PREP_SH_URI]'$DOCKER_PREP_SH_URI'"
              MASTER_IMAGES_URI=`cat scripts/MASTER_IMAGES_LINK.txt`
              echo $MASTER_IMAGES_URI
              echo "##vso[task.setvariable variable=MASTER_IMAGES_URI]'$MASTER_IMAGES_URI'"
              NODE_IMAGES_URI=`cat scripts/NODE_IMAGES_LINK.txt`
              echo $NODE_IMAGES_URI
              echo "##vso[task.setvariable variable=NODE_IMAGES_URI]'$NODE_IMAGES_URI'"
              INFRA_1_IMAGES_URI=`cat scripts/INFRA_1_IMAGES_LINK.txt`
              echo $INFRA_1_IMAGES_URI
              echo "##vso[task.setvariable variable=INFRA_1_IMAGES_URI]'$INFRA_1_IMAGES_URI'"
              INFRA_2_IMAGES_URI=`cat scripts/INFRA_2_IMAGES_LINK.txt`
              echo $INFRA_2_IMAGES_URI
              echo "##vso[task.setvariable variable=INFRA_2_IMAGES_URI]'$INFRA_2_IMAGES_URI'"
              INFRA_3_IMAGES_URI=`cat scripts/INFRA_3_IMAGES_LINK.txt`
              echo $INFRA_3_IMAGES_URI
              echo "##vso[task.setvariable variable=INFRA_3_IMAGES_URI]'$INFRA_3_IMAGES_URI'"
              INFRA_LOGGING_IMAGES_URI=`cat scripts/INFRA_LOGGING_IMAGES_LINK.txt`
              echo $INFRA_LOGGING_IMAGES_URI
              echo "##vso[task.setvariable variable=INFRA_LOGGING_IMAGES_URI]'$INFRA_LOGGING_IMAGES_URI'"
              INFRA_METRICS_IMAGES_URI=`cat scripts/INFRA_METRICS_IMAGES_LINK.txt`
              echo $INFRA_METRICS_IMAGES_URI
              echo "##vso[task.setvariable variable=INFRA_METRICS_IMAGES_URI]'$INFRA_METRICS_IMAGES_URI'"
              REGISTRY_IMAGE_URI=`cat scripts/REGISTRY_IMAGE_LINK.txt`
              echo $REGISTRY_IMAGE_URI
              echo "##vso[task.setvariable variable=REGISTRY_IMAGE_URI]'$REGISTRY_IMAGE_URI'"
              REG_CERT_URI=`cat scripts/REG_CERT_LINK.txt`
              echo $REG_CERT_URI
              echo "##vso[task.setvariable variable=REG_CERT_URI]'$REG_CERT_URI'"
              REG_KEY_URI=`cat scripts/REG_KEY_LINK.txt`
              echo $REG_KEY_URI
              echo "##vso[task.setvariable variable=REG_KEY_URI]'$REG_KEY_URI'"
            displayName: 'Load links into the pipeline'
          - script: |
              echo $(ANSIBLE_URI)
              wget -O $(Build.SourcesDirectory)/tansible-rpms.tar $(ANSIBLE_URI)
            displayName: 'Test SAS link connectivity'
          - task: AzurePowerShell@4
            displayName: 'Update Parameters File'
            inputs:
              azureSubscription: $(RESOURCE_MANAGER_SERVICE_CONNECTION)
              scriptType: 'FilePath'
              scriptPath: 'scripts/updateParameters.ps1'
              scriptArguments: $(Build.SourcesDirectory) $(MASTER_COUNT) $(INFR_COUNT) $(NODE_COUNT) $(OS_ADMIN_USER_NAME) $(OS_ADMIN_PASSWORD) "$(SSH_PUBLIC_KEY)" $(KEYVAULT_RESOURCE_GROUP) $(KEYVAULT_NAME) $(AAD_CLIENT_ID) $(AAD_CLIENT_SECRET) $(OPENSHIFT_CLUSTER_PREFIX) $(NETWORK_RESOURCE_GROUP) $(VNET_NAME) $(MASTER_SUBNET_NAME) $(NODE_SUBNET_NAME) $(MASTER_NETWORK_SECURITY_GROUP_NAME) $(INFRASTRUCTURE_NETWORK_SECURITY_GROUP_NAME) $(NODE_NETWORK_SECURITY_GROUP_NAME) $(ENABLE_PUBLIC_ACCESS) $(INFRASTRUCTURE_PUBLIC_IP_DNS_LABEL) $(OPENSHIFT_MASTER_PUBLIC_IP_DNS_LABEL) $(INFRASTRUCTURE_STATIC_PRIVATE_IP) $(OPENSHIFT_STATIC_PRIVATE_IP) $(NODE_PREP_SH_URI) $(MASTER_PREP_SH_URI) $(INFRA_PREP_SH_URI) $(DOCKER_PREP_SH_URI) $(DEPLOY_OPENSHIFT_SH_URI) $(CLUSTERNODE_JSON_URI) $(OPENSHIFT_DEPLOY_JSON_URI) $(ANSIBLE_URI) $(OPENSHIFT_ANSIBLE_URI) $(OPENSHIFT_CONTAINER_PLATFORM_PLAYBOOKS_URI) $(OPENSHIFT_ORIGIN_RPMS_URI) $(MASTER_IMAGES_URI) $(NODE_IMAGES_URI) $(INFRA_1_IMAGES_URI) $(INFRA_2_IMAGES_URI) $(INFRA_3_IMAGES_URI) $(INFRA_LOGGING_IMAGES_URI) $(INFRA_METRICS_IMAGES_URI) $(REGISTRY_IMAGE_URI) $(REG_CERT_URI) $(REG_KEY_URI)
              azurePowerShellVersion: 'LatestVersion'
          - task: AzurePowerShell@4
            displayName: 'Read Parameters File'
            inputs:
              azureSubscription: $(RESOURCE_MANAGER_SERVICE_CONNECTION)
              scriptType: 'FilePath'
              scriptPath: 'scripts/readParamsFile.ps1'
              scriptArguments: $(Build.SourcesDirectory)
              azurePowerShellVersion: 'LatestVersion'
          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy Openshift Origin Cluster'
            inputs:
              azureSubscription: $(RESOURCE_MANAGER_SERVICE_CONNECTION)
              resourceGroupName: $(RESOURCE_GROUP)
              # location is ignored if the resource group already exists
              location: 'East US'
              csmFile: 'azuredeploy.json'
              csmParametersFile: 'azuredeploy.parameters.json'
